run_name: base

wandb:
  project: FoundOpt

data:
  dataset_path: /anvme/workspace/b250be13-opt/data/sineCos/single/1D_bench
  transform_type: null
  models_path: "/anvme/workspace/b250be13-opt/data/sineCos/single/1D_bench/models_0.dill"
  version: 0_99

model:
  input_dim: !!int 2
  hidden_dim: !!int 64
  num_layers: !!int 2
  num_heads: !!int 2
  dropout: !!float 0.3
  num_bins: !!int 32
  use_positional_encoding: true
  use_autoregressive: true
  loss_type: ce
  bar_dist_smoothing: !!float 0.0
  full_support: false

optimizer:
  lr: !!float 1e-4
  weight_decay: !!float 1e-5
  scheduler:
    warmup_fraction: !!float 0.1
    plateau_fraction: !!float 0.3

training:
  batch_size: !!int 512
  epochs: !!int 50
  ckpt_dir: "./checkpoints"
  save_every: !!int 5

losses:
  exploration_weight: !!float 0.0
  convergence_weight: !!float 0.0
